config/routes.rb
LocationTracker::Application.routes.draw do
  authenticated :user do
    root :to => 'home#show'
  end
  root :to => "home#index"
  devise_for :users


  resources :members do
    collection do
      get 'email'
      get 'success'
    end
  end

  resources :locations

  resources :tags do
    collection do
      get 'massdel'
    end
  end

  









end

app/models/location.rb
class Location < ActiveRecord::Base
	attr_accessible :latitude, :longitude, :id, :name

end

app/models/member.rb
class Member < ActiveRecord::Base
  attr_accessible :name, :email, :role
  has_many :tags
  
  #sortin the list of members so that first click is ascending and the second click is descending
  @asc = true
  def self.asc=(val)
	@asc = val
  end
  
  def self.asc
    return @asc
  end
  
end

app/models/tags.rb
class Tags < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :label, :user_id
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :tags
	has_many :locations

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :role, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def show()

    @autocomplete_people = User.all.map(&:name).uniq
  	@locations = [[37.488902,-122.230657, 'HeadQuarter','']]
  	@tracing = false
    
	  if Location.count != 0
      if params[:search_name] == nil or params[:search_name] == ""
        if params[:search_time] == nil or params[:search_time] == "" or params[:search_time] == 0
          session.delete(:search_time)
          @geolocations = Location.all
        else
          session[:search_time] = params[:search_time]
          @geolocations = Location.where(:updated_at => params[:search_time].to_i.minutes.ago..Time.now)
        end
        
      else

        if session[:search_time] == nil or session[:search_time] == "" or session[:search_time] == 0
          @geolocations = Location.where("name = ?", params[:search_name])
        else
          @geolocations = Location.where(:updated_at => session[:search_time].to_i.minutes.ago..Time.now).where("name = ?", params[:search_name])
        end

        #@geolocations = Location.where("name = ?", params[:search_name])
        @tracing = true
        
      end
    @geolocations.each{ |locate| @locations.push([locate.latitude,locate.longitude, locate.name, locate.updated_at.to_s])}
    end
    #puts "---------------******************_----------------------**************--------------------"
    #puts @locations
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
	
	def show
		id = params[:id]
		@location = Location.find(id)
	end

	def index
		@locations = Location.all
		#Sorting the list of locations ascending the first click then by descending the second click
		if (params[:sort] == 'name')
			if ((not session[:sort_name]) or session[:sort_name] == 'ascend')
				@locations = Location.find(:all, :order => 'name ASC')
				session[:sort_name] = 'descend'
			else
				@locations = Location.find(:all, :order => 'name DESC')
				session[:sort_name] = 'ascend'
			end
		end
		if (params[:sort] == 'time')
			if ((not session[:sort_time]) or session[:sort_time] == 'ascend')
				@locations = Location.find(:all, :order => 'updated_at ASC')
				session[:sort_time] = 'descend'
			else
				@locations = Location.find(:all, :order => 'updated_at DESC')
				session[:sort_time] = 'ascend'
			end
		end
	end

	def create
		@location = Location.new
		@location.longitude = params[:longitude]
		@location.latitude = params[:latitude]
		#puts"**********************************************************"
		@location.name = current_user.name
		#puts @location.name
		if params[:id]
			@location.id = params[:id]
		end
	    if @location.save!
	    	flash[:notice] = "Location successfully saved"
	    	redirect_to locations_path
	    end
    end

	def update
		@location = Location.find(params[:id])
		@location.longitude = params[:longitude]
		@location.latitude = params[:latitude]
		@location.name = current_user.name
		#puts "---------------------------------------------------------"
		#puts @location.name
		if @location.save!
			flash[:notice] = "Location successfully updated"
			redirect_to locations_path
		end
	end

	def destroy
		@location = Location.find(params[:id])
		@location.destroy
		flash[:notice] = "Location data deleted"
		redirect_to locations_path
	end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController

  def show
  end

  def index
    @members = User.all
    #sort by name, ascending then descending
    if (params[:sort] == 'name')
		if ((not session[:sort_name]) or session[:sort_name] == 'ascend')
			@members = User.find(:all, :order => 'name ASC')
			session[:sort_name] = 'descend'
		else
			@members = User.find(:all, :order => 'name DESC')
			session[:sort_name] = 'ascend'
		end
	end
	#sort by email, ascending then descending
	if (params[:sort] == 'email')
		if ((not session[:sort_email]) or session[:sort_email] == 'ascend')
			@members = User.find(:all, :order => 'email ASC')
			session[:sort_email] = 'descend'
		else
			@members = User.find(:all, :order => 'email DESC')
			session[:sort_email] = 'ascend'
		end
	end
	if (params[:sort] == 'role')
		if ((not session[:sort_role]) or session[:sort_role] == 'ascend')
			@members = User.find(:all, :order => 'role ASC')
			session[:sort_role] = 'descend'
		else
			@members = User.find(:all, :order => 'role DESC')
			session[:sort_role] = 'ascend'
		end
	end	
	
	
  end

  def new
  end

  def create
    @members = User.create!(params[:member])
    redirect_to members_path
  end


  def email		
    #if params[:members_all]
      #@members = User.all
    #else
      @members_temp = (params[:members]? params[:members].keys : [])
		  @members = User.find(:all, :conditions => {:name => @members_temp})
    #end

		#puts @members.length
		if @members.length == 0
			flash[:notice] = "No members available"
			redirect_to "/members"
		else
			@members.each do |member|
				UserMailer.seek_email(member).deliver
			end
			redirect_to success_members_path(:members => params[:members], :members_all => params[:members_all])
		end
  end
	
  def success
    if params[:members_all]
      @members = User.all
    else
      @members_temp = (params[:members]? params[:members].keys : [])
		  @members = User.find(:all, :conditions => {:name => @members_temp})
    end
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @members = User.all
    @tags = Tags.all
	end

  def create
    @users = User.find(params[:members].values)
    @users.each do |user|
      Tags.create!(:user_id=>user.id, :label => params[:tagname])
    end
    redirect_to members_path
  end

  def massdel
    params.keys.each do |uniqtag|
      if params[uniqtag]==uniqtag
        Tags.where(:label => uniqtag).destroy_all
      end
    end
    redirect_to members_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def resource_name
  	:user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/home/_map.html.haml
!!! XML
!!!
%html{:lang => "en"}
  %head
    %meta{:name => "viewport", :content => "initial-scale=1.0, user-scalable=no"}
      :css
        html{
          height:100%;
        }
        body{
          height: 100%;
          margin: 0;
          padding: 0;
        }
        #map-canvas{
          height: 100%;
        }
      %script{:src => "https://maps.googleapis.com/maps/api/js?key=AIzaSyD3AGyItogf6M4YJzUNnJHDeTjwFoMVHT4&sensor=true", :type => "text/javascript"}
      = javascript_include_tag "/javascripts/map.js"
      
  %body
    %br

    %div#map-canvas	
    :javascript 
      var locations = #{@locations};
      var tracing = #{@tracing};
      if(tracing){
        trace_map(locations);
      }
      else{
        initialize(locations);
      }

app/views/home/_search.html.erb
<html>
<head>
    <script type="text/javascript" src="http://code.jquery.com/jquery-latest.js"></script>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.9/jquery-ui.js"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            var data = (#{@autocomplete_people.to_json});
            $("#search").autocomplete({source:data});
        });
    </script>
</head>

<body>
    <input id="search" type="text"/>
</body>
</html>

app/views/home/_topbar.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}
      %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
        %meta{:content => "", :name => "description"}
          %meta{:content => "", :name => "author"}
            %link{:href => "../../assets/ico/favicon.png", :rel => "shortcut icon"}
              %title BAMRU Location Tracker
              / Latest compiled and minified CSS
              %link{:href => "//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css", :rel => "stylesheet"}
              %stylesheet_link_tag "typeahead.css"


  %body
    .navbar.navbar-default.navbar-fixed-top
      .container
        .navbar-header
          %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{:href => "#"} BAMRU Location Tracker
        .navbar-collapse.collapse
          %ul.nav.navbar-nav
            %li.active
              %a{:href => "/"} Home
            - if user_signed_in? 
              %li
                %a{:href => "/members"} Send Location Request
              %li
                %a{:href => "/locations"} Log Location
              %li.dropdown
                %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                  Locations by time
                  %span.caret
                %ul.dropdown-menu
                  %li{:role => "presentation"}= link_to "15 min", root_path(:search_time => 15)
                  %li{:role => "presentation"}= link_to "30 min", root_path(:search_time => 30)
                  %li{:role => "presentation"}= link_to "1 hour", root_path(:search_time => 60)
                  %li{:role => "presentation"}= link_to "3 hours", root_path(:search_time => 180)
                  %li{:role => "presentation"}= link_to "6 hours", root_path(:search_time => 360)
                  %li{:role => "presentation"}= link_to "12 hours", root_path(:search_time => 720)
                  %li{:role => "presentation"}= link_to "1 day", root_path(:search_time => 1440)
                  %li{:role => "presentation"}= link_to "3 days", root_path(:search_time => 4320)
                  %li{:role => "presentation"}= link_to "1 week", root_path(:search_time => 10080)
                  %li{:role => "presentation"}= link_to "1 month", root_path(:search_time => 43829)
                  %li{:role => "presentation"}= link_to "1 year", root_path(:search_time => 525949)
              %li
                = form_tag({:action => 'show', :controller => 'home'}, {:class => 'navbar-form'}) do
                  = text_field_tag :search_name, params[:search_name], :class=> "typeahead", data: {provide: 'typeahead'}, :placeholder => "Search locations by name"
                  = submit_tag :Search, {:id => "search_submit", :class => "btn btn-success button"}
              %li
                = link_to "Sign out", destroy_user_session_path, :method => :delete
          - if not user_signed_in?
            %ul.nav.navbar-nav.navbar-right
              %li= link_to "Sign up", new_user_registration_path
            %form.navbar-form.navbar-right
              .form-group
                %input.form-control{:placeholder => "Email", :type => "text"}
              .form-group
                %input.form-control{:placeholder => "Password", :type => "password"}
              %button.btn.btn-success{:type => "submit"}= link_to "Sign in", new_user_session_path
        / /.navbar-collapse
      / /container
      /
        Bootstrap core JavaScript
        \==================================================
      / Placed at the end of the document so the pages load faster
      %script{:src => "//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"}
      / Latest compiled and minified JavaScript
      %script{:src => "//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"}
      %script{:src =>"//twitter.github.com/typeahead.js/releases/latest/typeahead.bundle.js"}
      :javascript
        var data = #{@autocomplete_people.to_json};
          $(".typeahead").typeahead({
            name: 'search_name',
            local: data
          }); 
        $('.dropdown-toggle').dropdown();

      

app/views/home/index.html.haml
!!!
%html
  %head
    %title BAMRU Location Tracker
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    / Bootstrap
    %link{:href => "//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css", :rel => "stylesheet"}
      %link{:href => "//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css", :rel => "stylesheet"}/
      %link{:href => "http://fonts.googleapis.com/css?family=Abel|Open+Sans:400,600", :rel => "stylesheet"}/
      :css
        /* http://css-tricks.com/perfect-full-page-background-image/ */
        html {
          background: url("http://farm4.staticflickr.com/3678/9071700493_2044321565_h.jpg") no-repeat center center fixed; 
          -webkit-background-size: cover;
          -moz-background-size: cover;
          -o-background-size: cover;
          background-size: cover;
        }

        body {
          padding-top: 20px;
          font-size: 16px;
          font-family: "Open Sans",serif;
          background: transparent;
        }

        h1 {
          font-family: "Abel", Arial, sans-serif;
          font-weight: 400;
          font-size: 40px;
        }

        /* Override B3 .panel adding a subtly transparent background */
        .panel {
          background-color: rgba(255, 255, 255, 0.9);
        }

        .margin-base-vertical {
          margin: 40px 0;
        }

    %body
    .container
      .row
        .col-md-6.col-md-offset-3.panel.panel-default
          %h1.margin-base-vertical Welcome to BAMRU Location Tracker!
          %h2 Sign in
          = form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f|
            %p.input-group
              %span.input-group-addon
                %span.icon-envelope
              = f.email_field :email, :autofocus => true, :placeholder => "Email, ex: bamru@bamru.org", :class => "form-control input-lg"
            %p.input-group
              %span.input-group-addon
                %span.icon-lock  
              = f.password_field :password, :placeholder => "Password", :class => "form-control input-lg"
            - if devise_mapping.rememberable?
              .checkbox
                = f.check_box :remember_me
                = f.label :remember_me
            %p.text-center
              = f.submit "Sign in", :class =>'btn btn-primary btn-lg'
          = render "devise/shared/links"
          .margin-base-vertical
            %small.text-muted
              %a{:href => "http://farm4.staticflickr.com/3678/9071700493_2044321565_h.jpg"}> Background picture by Nick Freeman @flickr
          %p.help-block.text-center
            %small &copy; BAMRU 2013
        / //main content
      / //row
    / //container

app/views/home/oldindex.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}
      %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
        %meta{:content => "", :name => "description"}
          %meta{:content => "", :name => "author"}
            %link{:href => "../../assets/ico/favicon.png", :rel => "shortcut icon"}
              %title BAMRU Location Tracker
              / Latest compiled and minified CSS
              %link{:href => "//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css", :rel => "stylesheet"}
                / HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
                /[if lt IE 9]
                  <script src="../../assets/js/html5shiv.js"></script>
                  <script src="../../assets/js/respond.min.js"></script>
  %body
    = render 'home/topbar'
    / Main jumbotron for a primary marketing message or call to action
    .jumbotron
      .container
        %h1 Hello BAMRU & Team!
        %img.img-rounded{:alt => "BAMRU", :src => "http://bamru.org/images/TopBanner.jpg"}
          %img.img-rounded{:alt => "BAMRU", :src => "http://bamru.org/images/BottomBanner.jpg"}
    %hr
      %footer
        %p &copy; BAMRU 2013
      / /container
      /
        Bootstrap core JavaScript
        \==================================================
      / Placed at the end of the document so the pages load faster
      %script{:src => "//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"}
      / Latest compiled and minified JavaScript
      %script{:src => "//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"}
      

app/views/home/show.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}
      %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
        %meta{:content => "", :name => "description"}
          %meta{:content => "", :name => "author"}
            %link{:href => "../../assets/ico/favicon.png", :rel => "shortcut icon"}
              %title BAMRU Location Tracker
              / Latest compiled and minified CSS
              %link{:href => "//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css", :rel => "stylesheet"}
              
  %body
    = render 'home/topbar'
    = render 'home/map'


Bootstrap core JavaScript
\==================================================
/ Placed at the end of the document so the pages load faster
%script{:src => "//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"}
/ Latest compiled and minified JavaScript
%script{:src => "//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"}
      

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LocationTracker</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= content_tag(:div, flash[:error], :id => "flash_error") if flash[:error] %>
  <%= content_tag(:div, flash[:notice], :id => "flash_notice") if flash[:notice] %>
  <%= content_tag(:div, flash[:alert], :id => "flash_alert") if flash[:alert] %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/locations/create.js.erb
$('#geoLocation').html("<%=h @message.html_safe %>");

app/views/locations/index.html.erb
<% content_for :javascript_includes do %>
	<%= javascript_include_tag "geolocation.js" %>
<% end %>	
<%= csrf_meta_tag %>
<%= stylesheet_link_tag "location"%>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

<h3 id="location_show"></h3>

<%= button_to "Home", {controller: "home"}, id:"location_home_link", class:"location_button"%>


<% if user_signed_in? %>

	<table id="location_table">
		<thead>
			<tr>
				<th class="location_row"> <%= link_to "Name", locations_path(:sort => "name"), :id => "sort_name" %> </th>
				<th class="location_row"> Longitude </th>
				<th class="location_row"> Latitude </th>
				<th class="location_row"> <%= link_to "Time", locations_path(:sort => "time"), :id => "sort_time" %> </th>
			</tr>
		</thead>
		<tbody>
			<%- @locations.each do |location| %>
			<tr class="full_row">
				<td class="location_row"> <%= location.name %> </td>
				<td class="location_row"> <%= location.longitude %> </td>
				<td class="location_row"> <%= location.latitude %> </td>
				<td class="location_row"> <%= location.updated_at %> </td>
			</tr>
			<%- end %>
		</tbody>
	</table>




	<button name="find_my_location", id="find_my_location", class="location_button">
		Find My Location
	</button>
	
	<!-- Show the locations table with the various times -->
<% else %>
	<div id="sign_in">
		<!-- Show the login to get the user credentials -->
		<h3> Sign in to share location </h3>
		<!-- Potentially set a flag here to tell the registration to redirect back here -->
		<div id="form">
			<%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
				<%= f.email_field :email, :autofocus => true, :placeholder => "Email" %>
				<%= f.password_field :password, :placeholder => "Password" %>
				<% if devise_mapping.rememberable? %>
					<%= f.check_box :remember_me %>
					<%= f.label :remember_me %>
				<% end %>
				<%= f.submit "Sign in" %>
			<% end %>
		</div>
		<%= link_to "Sign up for new users", new_user_registration_path %>
	</div>
<% end %>

app/views/members/_topbar.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}
      %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
        %meta{:content => "", :name => "description"}
          %meta{:content => "", :name => "author"}
            %link{:href => "../../assets/ico/favicon.png", :rel => "shortcut icon"}
              %title BAMRU Location Tracker
              / Latest compiled and minified CSS
              %link{:href => "//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css", :rel => "stylesheet"}


  %body
    .navbar.navbar-default.navbar-fixed-top
      .container
        .navbar-header
          %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{:href => "#"} BAMRU Location Tracker
        .navbar-collapse.collapse
          %ul.nav.navbar-nav
            %li.active
              %a{:href => "/"} Home
            - if user_signed_in?
              %li
                %a{:href => "/locations"} Log Location
              %li
                = link_to "Sign out", destroy_user_session_path, :method => :delete
          - if not user_signed_in?
            %ul.nav.navbar-nav.navbar-right
              %li= link_to "Sign up", new_user_registration_path
            %form.navbar-form.navbar-right
              .form-group
                %input.form-control{:placeholder => "Email", :type => "text"}
              .form-group
                %input.form-control{:placeholder => "Password", :type => "password"}
              %button.btn.btn-success{:type => "submit"}= link_to "Sign in", new_user_session_path
        / /.navbar-collapse
      / /container
      /
        Bootstrap core JavaScript
        \==================================================
      / Placed at the end of the document so the pages load faster
      %script{:src => "//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"}
      / Latest compiled and minified JavaScript
      %script{:src => "//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"}
      

app/views/members/index.html.haml
-#  This file is app/views/members/index.html.haml

%link{:href => "//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css", :rel => "stylesheet"}

-if not flash.empty?
	= flash[:notice]


%br
%br
%h1 Member to Member Query

= render 'members/topbar'

%p Select Tags:
All
= check_box_tag("members_all", "members_all", false, :onclick => "checkAll(this)")
- Tags.uniq.pluck(:label).sort.each do |tag|
	= tag 
	=check_box_tag("#{tag}", "#{tag}", false, :onclick => "checkTag(this)")


%table.table.table-condensed#members
	%thead
		%tr
			%th= link_to "Name", members_path(:sort => 'name'), :id => 'sort_name'
			%th= link_to "Email", members_path(:sort => 'email'), :id => 'sort_email'
			%th= link_to "Role", members_path(:sort => 'role'), :id => 'sort_role'
			%th Tags
			%th Select
	%tbody

	= form_tag "members/email", :method => :get, :id => 'send_form' do
		- @members.each do |member|
			%tr
				%td= member.name
				%td= member.email
				%td= member.role
				%td= labels = Tags.find_all_by_user_id(member.id).map{|record| record.label}*", "
				%td= check_box_tag("members[#{member.name}]", labels)
		.btn-group
			= submit_tag 'Send Request', :id => 'request_sent', :class => 'btn btn-success'
			= link_to 'Edit Tags', "/tags", method: "get", :class => 'btn btn-default'

app/views/members/show.html.haml
%h1 Successfully Sent

%b following people received emails:
%table#members
 %thead
  %tr
   %th Name
   %th Email
 %tbody
  - @members.each do |member|
   %td= member.name
   %td= member.email

app/views/members/success.html.haml
%link{:href => "//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css", :rel => "stylesheet"}

= render 'members/topbar'

%br
%br
%h1 Successfully Sent

%b The following people received location requests via email:
%table.table.table-condensed#members
 %thead
  %tr
   %th Name
   %th Email
   %th Role
 %tbody
  - @members.each do |member|
   %tr
    %td= member.name
    %td= member.email
    %td= member.role

app/views/tags/_topbar.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}
      %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
        %meta{:content => "", :name => "description"}
          %meta{:content => "", :name => "author"}
            %link{:href => "../../assets/ico/favicon.png", :rel => "shortcut icon"}
              %title BAMRU Location Tracker
              / Latest compiled and minified CSS
              %link{:href => "//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css", :rel => "stylesheet"}


  %body
    .navbar.navbar-default.navbar-fixed-top
      .container
        .navbar-header
          %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{:href => "#"} BAMRU Location Tracker
        .navbar-collapse.collapse
          %ul.nav.navbar-nav
            %li.active
              %a{:href => "/"} Home
            - if user_signed_in?
              %li
                %a{:href => "/members"} Back to Location Request
              %li
                %a{:href => "/locations"} Log Location
              %li
                = link_to "Sign out", destroy_user_session_path, :method => :delete
          - if not user_signed_in?
            %ul.nav.navbar-nav.navbar-right
              %li= link_to "Sign up", new_user_registration_path
            %form.navbar-form.navbar-right
              .form-group
                %input.form-control{:placeholder => "Email", :type => "text"}
              .form-group
                %input.form-control{:placeholder => "Password", :type => "password"}
              %button.btn.btn-success{:type => "submit"}= link_to "Sign in", new_user_session_path
        / /.navbar-collapse
      / /container
      /
        Bootstrap core JavaScript
        \==================================================
      / Placed at the end of the document so the pages load faster
      %script{:src => "//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"}
      / Latest compiled and minified JavaScript
      %script{:src => "//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"}
      

app/views/tags/index.html.haml
-#  This file is app/views/tags/index.html.haml
%link{:href => "//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css", :rel => "stylesheet"}

= render "tags/topbar"

%br
%br
%h1 New Tag
%p Tag Name

%table.table.table-condensed#members
	%thead
		%tr
			%th Name
			%th Email
			%th Role
			%th Select
	%tbody

	= form_tag tags_path, :method => :post, :id => 'send_form' do
		- @members.each do |member|
			%tr
				%td= member.name
				%td= member.email
				%td= member.role
				%td= check_box_tag("members[#{member.name}]", member.id)
		.form-inline
			.form-group
				= text_field_tag 'tagname', nil, :placeholder => "Tag name, ex: A-Team", :class => "form-control"
			= submit_tag 'Create Tag', :id => 'create_tag', :class => 'btn btn-success'


%h1 Delete Tag
= form_tag massdel_tags_path, :method => :get, :id => 'del_form' do
	- Tags.uniq.pluck(:label).sort.each do |uniqtag|
		= uniqtag 
		= check_box_tag("#{uniqtag}", "#{uniqtag}", false)
	= submit_tag 'Delete Tag', :id => 'remove_tag', :class => 'btn btn-danger'